# vim:set ft=dockerfile:
FROM       eudat-b2handle:python2.6

RUN        easy_install pip
RUN        pip install \
           argparse \
           coverage \
           mock \
           unittest2
RUN        pip install setuptools --upgrade

VOLUME     /opt/B2HANDLE/b2handle/tests

WORKDIR    /opt/B2HANDLE/b2handle/tests

COPY       docker-entrypoint.sh ./

ENTRYPOINT ["./docker-entrypoint.sh"]

CMD        ["coverage"]
