# vim:set ft=dockerfile:
FROM       eudat-b2handle:python2.6

RUN        easy_install pip
RUN        pip install \
           argparse \
           unittest2 \
           mock==2.0.0 \
           coverage==4.5.4 \
           nose

VOLUME     /opt/B2HANDLE/b2handle/tests

WORKDIR    /opt/B2HANDLE/b2handle/tests

COPY       docker-entrypoint.sh ./

ENTRYPOINT ["./docker-entrypoint.sh"]

CMD        ["coverage"]
